# Default values for Terraform Enterprise on Kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
imagePullSecrets:
- name: {}

image:
 repository: quay.io
 name: hashicorp/terraform-enterprise
 tag: latest
 pullPolicy: IfNotPresent
 pullSecret: terraform-enterprise

podAnnotations: {}

resources:
  requests:
    memory: "2500Mi"
    cpu: "750m"
  limits:
    memory: "7500Mi"
    cpu: "4000m"

tls:
  certificateSecret: terraform-enterprise-certificates
  caCertBaseDir: /etc/ssl/certs
  caCertFileName: custom_ca_certs.pem
  certMountPath: /etc/ssl/private/terraform-enterprise/cert.pem
  keyMountPath: /etc/ssl/private/terraform-enterprise/key.pem
  # certData:
  # keyData:
  # caCertData:

tfe:
    privateHttpPort: 8080
    privateHttpsPort: 8443

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}
    # runAsUser: 1000
    # runAsGroup: 3000
    # fsGroup: 2000

ingress:
  enabled: false
  className: "" # nginx
  annotations: {}
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
    - host: "" # "*.ptfe-dev.aws.ptfedev.com"
      paths:
        - path: /
          pathType: Prefix
          serviceName: "terraform-enterprise"
          portNumber: 443
  tls: []
    # - secretName: terraform-enterprise-certificates
    #   hosts:
    #   - "*.ptfe-dev.aws.ptfedev.com"

service:
  type: LoadBalancer # ClusterIP
  port: 443

env:
  TFE_ENCRYPTION_PASSWORD: "SUPERDUPERSECRET"
  TFE_HOSTNAME: "terraformernetes"
  TFE_IACT_SUBNETS: "0.0.0.0/0"
  TFE_IACT_TIME_LIMIT: "60"
  TFE_OPERATIONAL_MODE: "disk"
  TFE_TLS_VERSION: "tls_1_2_tls_1_3"
  TFE_VAULT_DISABLE_MLOCK: true
  # TFE_CAPACITY_CONCURRENCY: ""
  # TFE_CAPACITY_CPU: ""
  # TFE_CAPACITY_MEMORY: ""
  # TFE_DATABASE_HOST: ""
  # TFE_DATABASE_NAME: ""
  # TFE_DATABASE_PARAMETERS: ""
  # TFE_DATABASE_PASSWORD: ""
  # TFE_DATABASE_USER: ""
  # TFE_DISK_PATH: ""
  # TFE_OBJECT_STORAGE_AZURE_ACCOUNT_KEY: ""
  # TFE_OBJECT_STORAGE_AZURE_ACCOUNT_NAME: ""
  # TFE_OBJECT_STORAGE_AZURE_CONTAINER: ""
  # TFE_OBJECT_STORAGE_AZURE_ENDPOINT: ""
  # TFE_OBJECT_STORAGE_GOOGLE_BUCKET: ""
  # TFE_OBJECT_STORAGE_GOOGLE_CREDENTIALS: ""
  # TFE_OBJECT_STORAGE_GOOGLE_PROJECT: ""
  # TFE_OBJECT_STORAGE_S3_ACCESS_KEY_ID: ""
  # TFE_OBJECT_STORAGE_S3_BUCKET: ""
  # TFE_OBJECT_STORAGE_S3_ENDPOINT: ""
  # TFE_OBJECT_STORAGE_S3_REGION: ""
  # TFE_OBJECT_STORAGE_S3_SECRET_ACCESS_KEY: ""
  # TFE_OBJECT_STORAGE_S3_SERVER_SIDE_ENCRYPTION: ""
  # TFE_OBJECT_STORAGE_S3_SERVER_SIDE_ENCRYPTION_KMS_KEY_ID: ""
  # TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE: ""
  # TFE_OBJECT_STORAGE_TYPE: ""
  # TFE_REDIS_URL: ""
  # TFE_TLS_CIPHERS: ""
  # TFE_VAULT_ADDRESS: ""
  # TFE_VAULT_NAMESPACE: ""
  # TFE_VAULT_PATH: ""
  # TFE_VAULT_ROLE_ID: ""
  # TFE_VAULT_SECRET_ID: ""
