apiVersion: v1
kind: Service
metadata:
  name: terraform-enterprise
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.tfe.privateHttpsPort }}
  selector:
    app: terraform-enterprise
