name: Sox Check
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  sox-check:
    uses: hashicorp/tf-enterprise-workflows/.github/workflows/sox-check.yml@v0.3.14
